[package]
name = "core-db"
version.workspace = true
edition.workspace = true

[dependencies]
rusqlite.workspace = true
crossbeam-channel.workspace = true
serde.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
unicode-normalization = "0.1"

[dev-dependencies]
tempfile = "3"
